/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;


import Conceitos.Cliente;
import Conceitos.Funcionario;
import Conceitos.Imovel;
import Conceitos.LaudoTecnico;
import Conceitos.LaudoVistoria;
import Controle.ControladorCentral;
import javax.swing.*;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Roberto Augusto
 */
public class InterfaceCentralGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCentralGUI.class.getName());
    
    private ControladorCentral controladorCentral;

    /**
     * Creates new form InterfaceCentralGUI
     */
    public InterfaceCentralGUI() {
        controladorCentral = new ControladorCentral();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Registrar");

        jMenuItem1.setText("Registrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Registrar Aluguel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Registrar Funcionário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Registrar Gerente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Registrar Imóvel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Registrar Laudo Vistoria");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Registrar Laudo Técnico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Agendar");

        jMenuItem8.setText("Agendar Visita");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Agendar Vistoria");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Cliente",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();

            controladorCentral.registrarCliente(nome, email, celular);
            
            JOptionPane.showMessageDialog(this, "Cliente registrado.");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JTextField caucaoField = new JTextField(15);
        JTextField comissao_imobiliariaField = new JTextField(15);
        JTextField descontoField = new JTextField(15);
        JTextField funcionario_responsavelField = new JTextField(15);
        JTextField imovelField = new JTextField(15);
        JTextField locatarioField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Caução:"));
        panel.add(caucaoField);
        panel.add(new JLabel("Comissão imobiliária:"));
        panel.add(comissao_imobiliariaField);
        panel.add(new JLabel("Desconto:"));
        panel.add(descontoField);
        panel.add(new JLabel("Nome do funcionário responsável:"));
        panel.add(funcionario_responsavelField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(imovelField);
        panel.add(new JLabel("Nome do locatário:"));
        panel.add(locatarioField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Aluguel",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            int caucao = Integer.parseInt(caucaoField.getText());
            float comissao_imobiliaria = Float.parseFloat(comissao_imobiliariaField.getText());
            float desconto = Float.parseFloat(descontoField.getText());
            Funcionario funcionario_responsavel = controladorCentral.buscarFuncionarioPorNome(funcionario_responsavelField.getText());
            Imovel imovel = controladorCentral.buscarImovel(imovelField.getText());
            Cliente locatario = controladorCentral.buscarClientePorNome(locatarioField.getText());

            controladorCentral.registrarAluguel(caucao, comissao_imobiliaria, desconto, funcionario_responsavel, imovel, locatario);
            
            JOptionPane.showMessageDialog(this, "Aluguel registrado.");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JTextField salarioField = new JTextField(15);
        JTextField senhaField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);
        JTextField cpfField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Salário: "));
        panel.add(salarioField);
        panel.add(new JLabel("Senha: "));
        panel.add(senhaField);
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);
        panel.add(new JLabel("CPF:"));
        panel.add(cpfField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Funcionário",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            float salario = Float.parseFloat(salarioField.getText());
            String senha = senhaField.getText();
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();
            String cpf = cpfField.getText();

            controladorCentral.registrarFuncionario(salario, senha, nome, email, celular, cpf);
            
            JOptionPane.showMessageDialog(this, "Funcionario registrado.");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JTextField salarioField = new JTextField(15);
        JTextField senhaField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);
        JTextField cpfField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Salário: "));
        panel.add(salarioField);
        panel.add(new JLabel("Senha: "));
        panel.add(senhaField);
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);
        panel.add(new JLabel("CPF:"));
        panel.add(cpfField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Gerente",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            float salario = Float.parseFloat(salarioField.getText());
            String senha = senhaField.getText();
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();
            String cpf = cpfField.getText();

            controladorCentral.registrarGerente(salario, senha, nome, email, celular, cpf);
            
            JOptionPane.showMessageDialog(this, "Gerente registrado.");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JRadioButton ocupadoButton = new JRadioButton("Ocupado");
        JRadioButton desocupadoButton = new JRadioButton("Desocupado");

        ButtonGroup ocupacaoGroup = new ButtonGroup();
        ocupacaoGroup.add(ocupadoButton);
        ocupacaoGroup.add(desocupadoButton);

        JPanel ocupacaoPanel = new JPanel();
        ocupacaoPanel.add(ocupadoButton);
        ocupacaoPanel.add(desocupadoButton);
        
        JTextField nomeField = new JTextField(15);
        JTextField proprietarioField = new JTextField(15);
        JTextField tipoField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do imovel: "));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do proprietario: "));
        panel.add(proprietarioField);
        panel.add(new JLabel("Ocupacao:"));
        panel.add(ocupacaoPanel);
        panel.add(new JLabel("Tipo:"));
        panel.add(tipoField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Imóvel",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nome = nomeField.getText();
            Cliente proprietario = controladorCentral.buscarClientePorNome(proprietarioField.getText());
            boolean ocupacao = ocupadoButton.isSelected(); 
            int tipo = Integer.parseInt(tipoField.getText());
            LaudoTecnico laudo_tecnico = null;
            LaudoVistoria laudo_vistoria = null;

            controladorCentral.registrarImovel(nome, proprietario, ocupacao, tipo, laudo_tecnico, laudo_vistoria);
            
            JOptionPane.showMessageDialog(this, "Imóvel registrado.");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JTextField nome_laudoField = new JTextField(15);
        JTextField nome_imovelField = new JTextField(15);
        JTextField descricaoField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do laudo:"));
        panel.add(nome_laudoField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(nome_imovelField);
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Laudo Vistoria",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nome_laudo = nome_laudoField.getText();
            String nome_imovel = nome_imovelField.getText();
            String descricao = descricaoField.getText();

            controladorCentral.registrarLaudoVistoria(nome_laudo, nome_imovel, descricao);
            
            JOptionPane.showMessageDialog(this, "Laudo vistoria registrado.");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JTextField nome_laudoField = new JTextField(15);
        JTextField nome_imovelField = new JTextField(15);
        JTextField enderecoField = new JTextField(15);
        JTextField valor_imovelField = new JTextField(15);
        JTextField areaField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do laudo:"));
        panel.add(nome_laudoField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(nome_imovelField);
        panel.add(new JLabel("Endereço:"));
        panel.add(enderecoField);
        panel.add(new JLabel("Valor do imóvel:"));
        panel.add(valor_imovelField);
        panel.add(new JLabel("Área:"));
        panel.add(areaField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Registrar Laudo Técnico",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nome_laudo = nome_laudoField.getText();
            String nome_imovel = nome_imovelField.getText();
            String endereco = enderecoField.getText();
            float valor_imovel = Float.parseFloat(valor_imovelField.getText());
            float area = Float.parseFloat(areaField.getText());

            controladorCentral.registrarLaudoTecnico(nome_laudo, nome_imovel, endereco, valor_imovel, area);
            
            JOptionPane.showMessageDialog(this, "Laudo técnico registrado.");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        JTextField clienteField = new JTextField(15);
        JTextField funcionarioField = new JTextField(15);
        JTextField imovelField = new JTextField(15);
        JTextField data_horaField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do cliente:"));
        panel.add(clienteField);
        panel.add(new JLabel("Nome do funcionário:"));
        panel.add(funcionarioField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(imovelField);
        panel.add(new JLabel("Data e hora (dd/MM/yyyy HH:mm):"));
        panel.add(data_horaField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Agendar Visita",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            Cliente cliente = controladorCentral.buscarClientePorNome(clienteField.getText());
            Funcionario funcionario = controladorCentral.buscarFuncionarioPorNome(funcionarioField.getText());
            Imovel imovel = controladorCentral.buscarImovel(imovelField.getText());
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime data_hora = LocalDateTime.parse(data_horaField.getText(), fmt);

            controladorCentral.agendarVisita(cliente, funcionario, imovel, data_hora);
            
            JOptionPane.showMessageDialog(this, "Visita agendada.");
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JTextField clienteField = new JTextField(15);
        JTextField funcionarioField = new JTextField(15);
        JTextField imovelField = new JTextField(15);
        JTextField data_horaField = new JTextField(15);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do cliente:"));
        panel.add(clienteField);
        panel.add(new JLabel("Nome do funcionário:"));
        panel.add(funcionarioField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(imovelField);
        panel.add(new JLabel("Data e hora (dd/MM/yyyy HH:mm):"));
        panel.add(data_horaField);

        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Agendar Vistoria",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            Cliente cliente = controladorCentral.buscarClientePorNome(clienteField.getText());
            Funcionario funcionario = controladorCentral.buscarFuncionarioPorNome(funcionarioField.getText());
            Imovel imovel = controladorCentral.buscarImovel(imovelField.getText());
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime data_hora = LocalDateTime.parse(data_horaField.getText(), fmt);

            controladorCentral.agendarVistoria(cliente, funcionario, imovel, data_hora);
            
            JOptionPane.showMessageDialog(this, "Vistoria agendada.");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCentralGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
