/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;


import Controle.ControladorCentral;
import javax.swing.*;
import java.awt.GridLayout;

/**
 *
 * @author Roberto Augusto
 */
public class InterfaceCentralGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCentralGUI.class.getName());
    
    private ControladorCentral controladorCentral;

    /**
     * Creates new form InterfaceCentralGUI
     */
    public InterfaceCentralGUI() {
        controladorCentral = new ControladorCentral();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Registrar");

        jMenuItem1.setText("Registrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Registrar Aluguel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Registrar Funcionário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Registrar Gerente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Registrar Imóvel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Registrar Laudo Vistoria");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Registrar Laudo Técnico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // Criar campos
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);

        // Colocar os campos dentro de um painel
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);

        // Mostrar o JOptionPane com o painel
        int result = JOptionPane.showConfirmDialog(
            this,                // janela pai
            panel,               // conteúdo
            "Registrar Cliente", // título
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        // Se clicou em OK, pegar os valores
        if (result == JOptionPane.OK_OPTION) {
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();

            controladorCentral.registrarCliente(nome, email, celular);
            
            JOptionPane.showMessageDialog(this, "Cliente registrado.");

            // Aqui você chamaria seu controlador ou factory
            // controladorFuncionario.registrarCliente(nome, email, celular);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        // Criar campos
        JTextField salarioField = new JTextField(15);
        JTextField senhaField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);

        // Colocar os campos dentro de um painel
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Salário: "));
        panel.add(salarioField);
        panel.add(new JLabel("Senha: "));
        panel.add(senhaField);
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);

        // Mostrar o JOptionPane com o painel
        int result = JOptionPane.showConfirmDialog(
            this,                // janela pai
            panel,               // conteúdo
            "Registrar Funcionário", // título
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        // Se clicou em OK, pegar os valores
        if (result == JOptionPane.OK_OPTION) {
            float salario = Float.parseFloat(salarioField.getText());
            String senha = senhaField.getText();
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();

            controladorCentral.registrarFuncionario(salario, senha, nome, email, celular);
            
            JOptionPane.showMessageDialog(this, "Funcionario registrado.");

            // Aqui você chamaria seu controlador ou factory
            // controladorFuncionario.registrarCliente(nome, email, celular);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // Criar campos
        JTextField salarioField = new JTextField(15);
        JTextField senhaField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField emailField = new JTextField(15);
        JTextField celularField = new JTextField(15);

        // Colocar os campos dentro de um painel
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Salário: "));
        panel.add(salarioField);
        panel.add(new JLabel("Senha: "));
        panel.add(senhaField);
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Celular:"));
        panel.add(celularField);

        // Mostrar o JOptionPane com o painel
        int result = JOptionPane.showConfirmDialog(
            this,                // janela pai
            panel,               // conteúdo
            "Registrar Gerente", // título
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        // Se clicou em OK, pegar os valores
        if (result == JOptionPane.OK_OPTION) {
            float salario = Float.parseFloat(salarioField.getText());
            String senha = senhaField.getText();
            String nome = nomeField.getText();
            String email = emailField.getText();
            String celular = celularField.getText();

            controladorCentral.registrarGerente(salario, senha, nome, email, celular);
            
            JOptionPane.showMessageDialog(this, "Gerente registrado.");

            // Aqui você chamaria seu controlador ou factory
            // controladorFuncionario.registrarCliente(nome, email, celular);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        // Criar campos
        JTextField nome_laudoField = new JTextField(15);
        JTextField nome_imovelField = new JTextField(15);
        JTextField descricaoField = new JTextField(15);

        // Colocar os campos dentro de um painel
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do laudo:"));
        panel.add(nome_laudoField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(nome_imovelField);
        panel.add(new JLabel("Descrição"));
        panel.add(descricaoField);

        // Mostrar o JOptionPane com o painel
        int result = JOptionPane.showConfirmDialog(
            this,                // janela pai
            panel,               // conteúdo
            "Registrar Laudo Vistoria", // título
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        // Se clicou em OK, pegar os valores
        if (result == JOptionPane.OK_OPTION) {
            String nome_laudo = nome_laudoField.getText();
            String nome_imovel = nome_imovelField.getText();
            String descricao = descricaoField.getText();

            controladorCentral.registrarLaudoVistoria(nome_laudo, nome_imovel, descricao);
            
            JOptionPane.showMessageDialog(this, "Laudo vistoria registrado.");

            // Aqui você chamaria seu controlador ou factory
            // controladorFuncionario.registrarCliente(nome, email, celular);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        // Criar campos
        JTextField nome_laudoField = new JTextField(15);
        JTextField nome_imovelField = new JTextField(15);
        JTextField enderecoField = new JTextField(15);
        JTextField valor_imovelField = new JTextField(15);
        JTextField areaField = new JTextField(15);

        // Colocar os campos dentro de um painel
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do laudo:"));
        panel.add(nome_laudoField);
        panel.add(new JLabel("Nome do imóvel:"));
        panel.add(nome_imovelField);
        panel.add(new JLabel("Endereço:"));
        panel.add(enderecoField);
        panel.add(new JLabel("Valor do imóvel:"));
        panel.add(valor_imovelField);
        panel.add(new JLabel("Área:"));
        panel.add(areaField);

        // Mostrar o JOptionPane com o painel
        int result = JOptionPane.showConfirmDialog(
            this,                // janela pai
            panel,               // conteúdo
            "Registrar Laudo Vistoria", // título
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        // Se clicou em OK, pegar os valores
        if (result == JOptionPane.OK_OPTION) {
            String nome_laudo = nome_laudoField.getText();
            String nome_imovel = nome_imovelField.getText();
            String endereco = enderecoField.getText();
            float valor_imovel = Float.parseFloat(valor_imovelField.getText());
            float area = Float.parseFloat(areaField.getText());

            controladorCentral.registrarLaudoTecnico(nome_laudo, nome_imovel, endereco, valor_imovel, area);
            
            JOptionPane.showMessageDialog(this, "Laudo técnico registrado.");

            // Aqui você chamaria seu controlador ou factory
            // controladorFuncionario.registrarCliente(nome, email, celular);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCentralGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
